apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-api-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.env.ASPNETCORE_ENVIRONMENT | quote }}
  CORS__AllowedOrigins: {{ .Values.api.env.CORS__AllowedOrigins | quote }}
  AzureAd__Instance: {{ .Values.api.env.AzureAd__Instance | quote }}
  AzureAd__TenantId: {{ .Values.api.env.AzureAd__TenantId | quote }}
  OTEL_SERVICE_NAME: {{ .Values.api.env.OTEL_SERVICE_NAME | quote }}
