apiVersion: v1
kind: Secret
metadata:
  name: obsidian-api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
type: Opaque
stringData:
  AzureAd__ClientId: {{ .Values.api.env.AzureAd__ClientId | quote }}
  AzureAd__Audience: {{ .Values.api.env.AzureAd__Audience | quote }}
  ConnectionStrings__DefaultConnection: {{ .Values.api.env.ConnectionStrings__DefaultConnection | quote }}
